VOCAB_SITE/vocab/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

# app_name = 'vocab'

urlpatterns = [
    # redirect for just /vocab
    url(r'^$', RedirectView.as_view(url='/')),    

    url(r'^adminIRIs$', views.adminIRIs, name="adminIRIs"),
    url(r'^createIRI$', views.createIRI, name="createIRI"),
    url(r'^createUser$', views.createUser, name="createUser"),
    url(r'^createVocab$', views.createVocab, name="createVocab"),
    url(r'^searchResults$', views.searchResults, name="searchResults"),
    url(r'^iriCreationResults$', views.iriCreationResults, name="iriCreationResults"),
    url(r'^userProfile$', views.userProfile, name="userProfile"),
    url(r'^vocabulary/new$', views.vocabularyForm, name="vocabularyForm"),
    url(r'^vocabulary/(?P<vocab_name>[\w-]+)$', views.vocabulary, name="vocabulary"),
]

VOCAB_SITE/vocab_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vocab/', include('vocab.urls', namespace='vocab')),

    url(r'^$', views.home, name="home"),

#Are there any of these that we still need here or are we good??
    url(r'^accounts/login/$', auth_views.login, name="login"),
    url(r'^accounts/logout/$', views.logout_view, name="logout"),

]

VOCAB_SITE/vocab/models.py
from __future__ import unicode_literals

import json

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models, IntegrityError
from django.db.models.signals import post_save
from django.dispatch import receiver

from .tasks import notify_admins

TERM_TYPE_CHOICES = (
	('', ''),
	('verbs', 'Verbs'),
	('activityTypes', 'Activity Types'),
	('attachments', 'Attachments'),
	('extensions', 'Extensions')
)

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	def __unicode__(self):
		return json.dumps({"user": self.user.username, "registeredIRIs": [iri.return_address() for iri in self.registerediri_set.all()]})

class RegisteredIRI(models.Model):
	vocabulary_path = models.CharField(max_length=50)
	term_type = models.CharField(max_length=15, blank=True, choices=TERM_TYPE_CHOICES)
	term = models.CharField(max_length=50, blank=True)
	accepted = models.BooleanField(default=False)
	reviewed = models.BooleanField(default=False)
	userprofile = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL)

	def return_address(self):
		if self.term_type:
			if self.term:
				return settings.IRI_DOMAIN + "/".join([self.vocabulary_path, self.term_type, self.term])
			return settings.IRI_DOMAIN + "/".join([self.vocabulary_path, self.term_type])
		return settings.IRI_DOMAIN + self.vocabulary_path

	class Meta:
		unique_together = ("vocabulary_path", "term_type", "term")

	def save(self, *args, **kwargs):
		if self.term and not self.term_type:
			raise IntegrityError("Must supply a term type if supplying a term")
		super(RegisteredIRI, self).save(*args, **kwargs)

	def __unicode__(self):
		return json.dumps({"address": self.return_address(), "user": self.userprofile.user.username})

@receiver(post_save, sender=RegisteredIRI)
def iri_post_save(sender, **kwargs):
	if kwargs['created']:
		notify_admins.delay(kwargs['instance'].return_address())

class VocabularyData(models.Model):
	name = models.CharField(max_length=250)
	base_iri = models.OneToOneField(RegisteredIRI, blank=True, null=True, on_delete=models.SET_NULL)
	editorialNote = models.TextField()
	# what about copName, copUrl, dateCreated, dateModified, revisionNum, numTerms

	def __unicode__(self):
		return "%s" % (self.id, self.name)

class TermTypeData(models.Model):
	name = models.CharField(max_length=250)
	vocabulary_data = models.ForeignKey(VocabularyData)

	def __unicode__(self):
		return "%s:%s" % (self.vocabulary_data.name, self.name)

class TermData(models.Model):
	name = models.CharField(max_length=250)
	term_type_data = models.ForeignKey(TermTypeData)

	def __unicode__(self):
		return "%s:%s:%s" % (self.term_type_data__vocabulary_data.name, self.term_type_data.name, self.name)

VOCAB_SITE/vocab/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.formsets import BaseFormSet

from .models import RegisteredIRI, VocabularyData

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=200, label='Name')
    email = forms.EmailField(max_length=200, label='Email')
    password = forms.CharField(label='Password',
                                widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(label='Password Again',
                                widget=forms.PasswordInput(render_value=False))

    def clean(self):
        cleaned = super(RegisterForm, self).clean()
        p1 = cleaned.get("password")
        p2 = cleaned.get("password2")
        if p1 and p2:
            if p1 == p2:
                return cleaned
        raise forms.ValidationError("Passwords did not match")

class ContactForm(forms.Form):
    subject = forms.CharField(label='Subject', max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class SearchForm(forms.Form):
    search_term = forms.CharField(label='Search:', max_length=100)

class RegisteredIRIForm(ModelForm):
    class Meta:
        model = RegisteredIRI
        fields = ['vocabulary_path', 'term_type', 'term']
        widgets = {
            'vocabulary_path': forms.TextInput(attrs={'placeholder': 'Vocabulary/Profile', 'class': 'form-control'}),
            'term_type': forms.Select(attrs={'class': 'form-control'}),
            'term': forms.TextInput(attrs={'placeholder': 'Term', 'class': 'form-control'})
        }

    def clean(self):
        cleaned = super(RegisteredIRIForm, self).clean()
        term_type = cleaned.get("term_type", None)
        term = cleaned.get("term", None)
        if term and not term_type:
            raise forms.ValidationError("Must have a term type if giving a term")
        return cleaned

class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


    def clean(self):
        cleaned = super(RequiredFormSet, self).clean()
        form = self.forms[0]
        total = int(form.data['form-TOTAL_FORMS'])
        tuple_list = []
        for x in range(0, total):
            data_tuple = (form.data['form-'+str(x)+'-vocabulary_path'], form.data['form-'+str(x)+'-term_type'], \
                form.data['form-'+str(x)+'-term'])
            if data_tuple in tuple_list:
                raise forms.ValidationError("Forms cannot have the same triple values as other forms in the form set")
            else:
                tuple_list.append(data_tuple)

class VocabularyDataForm(forms.ModelForm):
    # vocabName = forms.CharField(label='Vocabulary Name', max_length=100)
    # vocabIRI = forms.URLField(label='Vocabulary IRI', max_length=100)
    class Meta:
        model = VocabularyData
        # fields = '__all__'
        exclude = ['user']

VOCAB_SITE/vocab/views.py
import logging

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse

from django.db import transaction, IntegrityError
from django.db.models import Q

from django.forms import formset_factory
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_http_methods

from .forms import RegisterForm, RegisteredIRIForm, SearchForm, RequiredFormSet, VocabularyDataForm
from .models import RegisteredIRI, UserProfile, VocabularyData
from .tasks import notify_user, update_htaccess

logger = logging.getLogger(__name__)

@require_http_methods(["GET"])
def home(request):
    return render(request, 'home.html')

@csrf_protect
@login_required
@require_http_methods(["GET", "POST"])
@transaction.atomic
def createIRI(request):
    RegisteredIRIFormset = formset_factory(RegisteredIRIForm, formset=RequiredFormSet)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        formset = RegisteredIRIFormset(request.POST)
        # check whether it's valid:
        if formset.is_valid():
            # process the data in form.cleaned_data as required
            for form in formset:
                if form.is_valid():
                    vocabulary_path = form.cleaned_data['vocabulary_path']
                    termType = form.cleaned_data['term_type']
                    term = form.cleaned_data['term']
                    profile = UserProfile.objects.get(user=request.user)
                    iriobj = RegisteredIRI.objects.create(vocabulary_path=vocabulary_path, term_type=termType, term=term, userprofile=profile)
            return render(request, 'iriCreationResults.html', {'newiri': iriobj.return_address()})
            #         # vocab = Vocabulary.objects.create
            #         termType = form.cleaned_data['termType']
            #         term = form.cleaned_data['term']
            #         # profile = UserProfile.objects.get(user=request.user)
            #         iriobj = RegisteredIRI.objects.create(vocab=vocabulary, term_type=termType, term=term, userprofile=profile)
            # return HttpResponseRedirect(reverse('iriCreationResults'))
            # # redirect to a new URL:

    # if a GET (or any other method) we'll create a blank form
    else:
        formset = RegisteredIRIFormset()
    return render(request, 'createIRI.html', {'formset': formset})

@csrf_protect
@require_http_methods(["POST", "GET"])
@transaction.atomic
def createUser(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'createUser.html', {"form": form})
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['username']
            pword = form.cleaned_data['password']
            email = form.cleaned_data['email']
            # If username doesn't already exist
            if not User.objects.filter(username__exact=name).count():
                # if email doesn't already exist
                if not User.objects.filter(email__exact=email).count():
                    user = User.objects.create_user(name, email, pword)
                    UserProfile.objects.create(user=user)
                else:
                    return render(request, 'createUser.html', {"form": form, "error_message": "Email %s is already registered." % email})
            else:
                return render(request, 'createUser.html', {"form": form, "error_message": "User %s already exists." % name})
            # If a user is already logged in, log them out
            if request.user.is_authenticated():
                logout(request)
            new_user = authenticate(username=name, password=pword)
            login(request, new_user)
            return HttpResponseRedirect(reverse('home'))
        else:
            return render(request, 'createUser.html', {"form": form})

@csrf_protect
@login_required
@require_http_methods(["GET", "POST"])
@transaction.atomic
def vocabularyForm(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = VocabularyDataForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            vocabName = form.cleaned_data['name']
            vocabIRI = form.cleaned_data['iri']
            print "hi andy", vocabIRI, vocabName
            vocabobj = VocabularyData.objects.create(name=vocabName, iri=vocabIRI, user=request.user)
            # redirect to a new URL:
            print reverse('vocab:vocabulary', args=('adl',))
            return HttpResponseRedirect(reverse('vocab:vocabulary', args=(vocabIRI.vocab,)))

    # if a GET (or any other method) we'll create a blank form
    # starting at the vocab portion of the iri
    else:
        form = VocabularyDataForm()

    return render(request, 'vocabularyForm.html', {'form': form})

@login_required
@require_http_methods(["GET"])
def userProfile(request):
    return render(request, 'userProfile.html')

@csrf_protect
@require_http_methods(["GET", "POST"])
def searchResults(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid:
            query = Q(vocabulary_path__contains=form.data['search_term']) | Q(term_type__contains=form.data['search_term']) \
                | Q(term__contains=form.data['search_term'])
            iris = RegisteredIRI.objects.filter(query & Q(accepted=True))
        return render(request, 'searchResults.html', {"form":form, "iris":iris})
    else:
        form = SearchForm()
    return render(request, 'searchResults.html', {"form":form})

@login_required()
@require_http_methods(["GET"])
def iriCreationResults(request):
    results = RegisteredIRI.objects.filter(userprofile__user = request.user)
    return render(request, 'iriCreationResults.html', {'iris':results})

@login_required()
@require_http_methods(["GET", "POST"])
@transaction.atomic
def adminIRIs(request):
    if request.user.is_superuser:
        iris = RegisteredIRI.objects.filter(accepted=False, reviewed=False)
        if request.method == "GET":
            return render(request, 'adminIRIs.html', {"iris": iris})
        else:
            vocabulary = request.POST['hidden-vocabulary_path']
            term_type = request.POST['hidden-term_type']
            term = request.POST['hidden-term']
            try:
                iri = RegisteredIRI.objects.get(vocabulary_path=vocabulary, term_type=term_type, term=term)
            except RegisteredIRI.DoesNotExist as dne:
                logger.exception(dne.message)
            else:
                if request.POST['action'] == "Accept":
                    iri.accepted = True
                    iri.reviewed = True
                    update_htaccess.delay("fake title", iri.vocabulary_path, "http://jsonld-redirect", "http://html-redirect")
                else:
                    iri.reviewed = True
                iri.save()
                notify_user.delay(iri.return_address(), iri.userprofile.user.email, iri.accepted)
        return render(request, 'adminIRIs.html', {"iris": iris})
    else:
        return HttpResponseForbidden()

@login_required()
@require_http_methods(["GET"])
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required()
@require_http_methods(["GET"])
def createVocab(request):
    return HttpResponseRedirect(reverse('home'))

# @csrf_protect
# @login_required()
# @require_http_methods(["GET"])
# def rdfaForm(request):
#     return render(request, 'rdfaForm.html')

@csrf_protect
@login_required()
@require_http_methods(["GET"])
def vocabulary(request, vocab_name):
    print vocab_name
    dispV = VocabularyData.objects.get(name=vocab_name)
    print dispV
    return render(request, 'vocabulary.html', {'vocab':vocab_name})

VOCAB_SITE/vocab/templates/adminIRIs.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div id="iriforms">
	{% for iri in iris %}
    <form action="{% url 'vocab:adminIRIs' %}" method="post">
        {% csrf_token %}
        <label for="hidden">{{ iri.return_address }}</label>
        <input type="hidden" name="hidden-vocabulary_path" value="{{ iri.vocabulary_path }}"/>
        <input type="hidden" name="hidden-term_type" value="{{ iri.term_type }}"/>
        <input type="hidden" name="hidden-term" value="{{ iri.term }}"/>
        <input type="submit" name="action" value="Accept" />
		<input type="submit" name="action" value="Reject" />
    </form>
	{% empty %}
	There are currently no pending IRIs.
	{% endfor %}

</div>

{% endblock content %}
{% block extra_js %}
{% endblock extra_js %}

VOCAB_SITE/vocab/templates/createIRI.html
{% extends "master.html" %}
{% load i18n %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p class="para">Welcome to the Create IRI Page.  Here you can access and submit the form to request a persistant IRI.  Have fun!</p>
    <hr>
    <form action="{% url 'vocab:createIRI' %}" class="form-inline" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ formset.non_form_errors }}
        <div class="forms">
            {% for form in formset %}
            <div id="form-{{ forloop.counter0 }}">
                {{ form.errors }}
                <big>https://w3id.org/xapi/ {{ form.vocabulary_path }} / {{form.term_type}} / {{form.term}}</big>
                <br>
            </div>
            {% endfor %}
        </div>
        <input class="btn btn-success" type="submit" value="Submit"/>
        <button type='button' class='btn btn-info' id="add-form"><span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Add IRI</button>
    </form>

    <hr>

</div>
<br>
{% endblock content %}

{% block extra_js %}
<script type="text/html" id='formtemplate'>
    <div id="form-__prefix__">
        <big>https://w3id.org/xapi/ {{ formset.empty_form.vocabulary_path }} / {{formset.empty_form.term_type}} / {{formset.empty_form.term}}</big>
        <br>
    </div>
</script>
<script type="text/javascript">
    $('#add-form').click(function(ev) {
        ev.preventDefault();
        var count = $('.forms').children().length;
        $('div.forms').append($('#formtemplate').html().replace(new RegExp('__prefix__', 'g'), count));
        $('#id_form-TOTAL_FORMS').attr('value', count+1);
    })
</script>
{% endblock extra_js %}

VOCAB_SITE/vocab/templates/createUser.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p class="para">Welcome to the Create User Page.  Here you can access and submit the form to create a user account with this page.  Mazel Tov!</p>
    <hr>
    {% if error_message %}
      <ul>
        <li>{{ error_message }}</li>
      </ul>
    {% endif %}
    <form class="" role="form" action="{% url 'vocab:createUser' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <!-- set this aside for a moment and try something different below this line which works -->
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    <hr>
</div>
{% endblock content %}

VOCAB_SITE/vocab/templates/home.html
{% extends "master.html" %}
{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p class="para" id="p1">Welcome to the xAPI Vocabulary Registry Page.  Here you can review other vocabularies and create you own vocabularies or individual terms.</p>
    <p class="para" id="p2">Anyone is welcome to search vocabularies to find the defined meaning of a given term or see if a new term is needed.</p>
    <p class="para" id="p3">If after considering existing terms you find that no term meets your groups needs, use your group's account or create an account and fill in the proper fields to create a new term or vocabulary.</p>
    <p class="para" id="p4">For Phase 1, emphasis is placed on establishing the ability to create a persistent IRI which will allow the creation of vocabularyies and terms. Therefore at this point Searching is disabled, please check back in the future.</p>
    <hr>
    Please Choose a Button:<br>
    <a type="button" class="btn btn-info" href="{% url 'vocab:createIRI' %}" role="button" name="createButton">Create</a>
    <a type="button" class="btn btn-info" href="{% url 'vocab:searchResults' %}" role="button" name="searchButton">Search</a>
</div>
{% endblock content %}

{% block extra_js %}
<!-- <script type="text/javascript" src="{% static "vocab/js/home.js" %}"></script> -->
{% endblock extra_js %}

VOCAB_SITE/vocab/templates/iriCreationResults.html
{% extends "master.html" %}
{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p>You submitted a new IRI to be created: {{ newiri }}. The review process takes at least 24 hours. You will be notified when the IRI has been
    accepted or denied.</p>
    <hr>
</div>
{% endblock content %}

VOCAB_SITE/vocab/templates/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Vocab Registry">
    <!-- Stylesheets needed for the whole site can go here -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static "vocab/css/master.css" %}">
    {% block extra_css %}<!-- This line holds stylesheets for individual pages if needed -->{% endblock extra_css %}
    <title>{% block title %}Vocab Registry{% endblock title %}</title>
</head>
<body>
<!-- Content here would be on every single page (like a login bar at the top or footer) -->
<div class="jumbotron">
    <div class="container text-center">
        <h1>xAPI Vocabulary Registry</h1>
        <h3>All the <strong>words</strong> in all the <strong>world!</strong></h3>
    </div>
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><img height="35" width="55" src="{% static "vocab/img/test.png" %}"/></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active" id="home"><a href="{% url 'home' %}">Home</a></li>
        <li id="createIRI"><a href="{% url 'vocab:createIRI' %}">Create IRI</a></li>
        <li id="createVocab"><a href="{% url 'vocab:vocabularyForm' %}">Create Vocabulary</a></li>
        <li id="createUser"><a href="{% url 'vocab:createUser' %}">Create New User</a></li>
        <li id="userProfile"><a href="{% url 'vocab:userProfile' %}">View User Profile</a></li>
        <li id="searchResults"><a href="{% url 'vocab:searchResults' %}">Search Results</a></li>
        {% if user.is_superuser %}<li id="adminIRIs"><a href="{% url 'vocab:adminIRIs' %}">Manage IRIs</a></li>{% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <div class="input-group col-sm-4">
              <input type="text" class="form-control" placeholder="Search Registry...">
              <span class="input-group-btn">
                  <button class="btn btn-default" type="button" href="{% url 'vocab:searchResults' %}" %}">
                      <span class="glyphicon glyphicon-search"></span>
                  </button>
              </span>
          </div>
        {% if user.is_authenticated %}
        <li><a href="{% url 'vocab:userProfile' %}">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span><span class="glyphicon glyphicon-log-in"></span> Account Login </a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}<!-- Individual page content goes here -->{% endblock content %}
</div>

<footer class="container-fluid text-center">
    <form class="form-inline">Email Sign Up:
        <input type="email" class="form-control" size="50" placeholder="Email Address">
        <button type="button" class="btn btn-danger">Sign Up</button>
    </form>
    <p>Copyright 2016 ADLnet.gov or xAPI Vocabulary Working Group | All Rights Reserved | Sponsored by the Office of the Under Secretary of Defense for Personnel and Readiness (OUSD P&amp;R)
    This is an official website of the U.S. Government © Advanced Distributed Learning</p>
</footer>

<!-- Full site javascript can go here if you wish-->
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- <script type="text/javascript" src="{% static "vocab/js/test.js" %}"></script> -->
{% block extra_js %}<!-- Individual page javascript goes here -->{% endblock extra_js %}
</body>
</html>

VOCAB_SITE/vocab/templates/searchResults.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p class="para">Welcome to the Search Results Page.  Below you should find all the words in all the world.  You asked for it, you got it!</p>
    <hr>
        <form class="" role="form" action="{% url 'vocab:searchResults' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <!-- set this aside for a moment and try something different below this line which works -->
        {{ form.as_p }}
        <input type="submit" value="Search" />
    </form>
    <hr>
    <ul>
    {% for iri in iris %}
    <li>{{ iri.return_address }}</li>
    {% empty %}
    No Results
    {% endfor %}
    </ul>
</div>
{% endblock content %}

VOCAB_SITE/vocab/templates/userProfile.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p class="para">Welcome to the User Profile Page.  Below you should find everything we know about you.  U B U!</p>
    <hr>
        <p>Hello {{ user.username }}!</p>
    <hr>
    <br>
    <ul>
    {% for iri in user.userprofile.registerediri_set.all %}
    <li>{{ iri.return_address }}</li>
    {% empty %}
    You have no IRIs registered
    {% endfor %}
    </ul>
</div>
{% endblock content %}

VOCAB_SITE/vocab/templates/vocabReceived.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p>
        "that's a lot of words are you finished now? <br> %s" % vocabulary
    </p>
    <p class="para">Welcome to the Create URI Page.  Here you can access and submit the form to request a persistant URI.  Have fun!</p>
    <hr>
</div>
{% endblock content %}

VOCAB_SITE/vocab/templates/vocabulary.html
{% extends "master.html" %}

{% block extra_css %}
<!-- This line holds stylesheets for individual pages if needed -->
{% load static %}
<link rel="stylesheet" href="{% static "vocab/css/home.css" %}">
{% endblock extra_css %}

{% block content %}
<div class="row content">
    <p>
        {{ vocab }}
    </p>
    <p>
        "that's a lot of words are you finished now? <br> %s" % vocabulary
    </p>
    <p class="para">Welcome to the Create URI Page.  Here you can access and submit the form to request a persistant URI.  Have fun!</p>
    <hr>
</div>
{% endblock content %}